### ISSUE TITLE
モテない

### ISSUE THREAD

**Issue by takanakahiko** [takanakahiko/takanakahiko#1]
ここらへんを頑張る

- [x] ゴッソで鼻毛を駆逐する
- [x] 体臭を消す
- [x] 差し歯が黒ずんでいるので，まともなやつにリプレイスする
- [ ] 青ひげがすごいので脱毛なりをする
- [ ] 腕が細すぎるので肉をつける
- [x] 姿勢が悪いので整体とかに行く
- [ ] 指先がボロボロなのでケアをする
- [ ] おしゃれな靴を買う

(reaction で応援いただけると嬉しいです)

**Comment by takanakahiko** [comment]
ゴッソの情報
https://www.amazon.co.jp/dp/B014IDL01C

**Comment by takanakahiko** [comment]
体臭予防に，これで定期的に体を拭いてみます

![IMG_0257](https://user-images.githubusercontent.com/10114717/60938618-80aa6b80-a30f-11e9-896a-4b934c4b45dc.JPG)

**Comment by takanakahiko** [comment]
「姿勢が悪いので整体とかに行く」をタスクリストに追加しました

**Comment by takanakahiko** [comment]
「指先がボロボロなのでケアをする」をタスクリストに追加

**Comment by takanakahiko** [comment]
ゴッソをamazonで注文しました

**Comment by lacolaco** [comment]
役に立つかどうかはわかりませんが、靴は案外けっこう見られてます。

**Comment by takanakahiko** [comment]
@lacolaco ありがとうございます！ABCマートは卒業ですね．

**Comment by takanakahiko** [comment]
「おしゃれな靴を買う」をタスクリストに追加

**Comment by lacolaco** [comment]
> @lacolaco ありがとうございます！ABCマートは卒業ですね．

広めのABCマートだと品揃えの幅も広いので良いと思いますよ！とりあえずカジュアルな革靴を探してみると良いと思います！

**Comment by UskeS** [comment]
自分が気をつけていることでもあるんですが、

# 容姿を整える
* 髪型：清潔感のある髪型
* 服装：割となんでも大丈夫だけどサイズ感と清潔感大事かも
* 靴や小物：あんまり派手でなくてよいが、自分がこだわっているところがあると良い

→ 容姿からその人のイメージが作られる

# コミュニケーションスキル
* 話の引き出しを増やす：相手にクラッチを合わせられるようにする
* 相手の話を最後まで聞く：相手の話を遮らない
* 相槌を上手につく：相手に話しやすい人という印象を与えやすい
* できるだけ自然体で接する：自分を作ってしまうと維持するのが無理ゲー
* 好きな人をたくさん作る：人のいいところが見つけやすくなる
* 嘘をつかない：誰にでも誠実であること

というところでどうでしょう。

**Comment by takanakahiko** [comment]
@lacolaco ABCマートでもいいんですね！広いところに行って，良さそうな革靴探してみます！

**Comment by takanakahiko** [comment]
@UskeS 盛りだくさんで嬉しいです！ありがとうございます！

服装のサイズ感は...気をつけます...(小さい頃から着ている服がある)
「できるだけ自然体で接する」というのがなかなかうまくいっていないので心がけようと思います！

**Comment by takanakahiko** [comment]
前職で，ファッション指南をしっかり受けるべきだったと後悔しています...

**Comment by takanakahiko** [comment]
「エアマックスを買うといい」とTwitterでアドバイスいただきました

**Comment by masaakikunsan** [comment]
スニーカーだったら俺はatmosで買ってるよ

**Comment by takanakahiko** [comment]
@masaakikunsan スポーティーな感じで良さそう．ありがとう!

**Comment by norinux** [comment]
女性に服をコーディネートしてもらうと、結果的に女子受けのよい服装になるのでオススメw

**Comment by takanakahiko** [comment]
@norinux 問題点として，服をコーディネートしてくれる女性が見つからないといったバグがあります...

**Comment by asmsuechan** [comment]
語学系のコミュニティは女性比率高い上にみんなマジメだからおすすめです(英語と韓国語を除く)

**Comment by tabunmuri** [comment]
@asmsuechan 何語ですか！何語なんですか！！！早く教えてください！！！こっちは人が死にかけてるんですよ！！！！

**Comment by takanakahiko** [comment]
基本的に私の魅力を如何に上昇させるか議論したいところですね...

**Comment by asmsuechan** [comment]
@tabunmuri C言語でも書いててください！！！

**Comment by yusukemisa** [comment]
魅力は既にあると思うのでとりあえずペアーズはじめよう。
![image](https://user-images.githubusercontent.com/25860926/61178735-1b67ba80-a62e-11e9-91df-0091b150e6b5.png)

**Comment by tabunmuri** [comment]
@asmsuechan ぜったいにゆるさない<○> <○>

**Comment by tabunmuri** [comment]
なるほど。
<img width="981" alt="スクリーンショット 2019-07-14 11 56 40" src="https://user-images.githubusercontent.com/8858625/61178744-79949d80-a62e-11e9-9022-8b55289fc567.png">

**Comment by prprhyt** [comment]
>  ゴッソで鼻毛を駆逐する

抜くの痛いし、衛生上の観点からも鼻毛カッターの方がよさそう(主観
僕はこれ使ってます。
パナソニック エチケットカッター 黒 ER-GN20-K
¥1,248
https://www.amazon.co.jp/dp/B005N3P7MK/ref=cm_sw_em_r_mt_dp_U_OaVkDbQYPJ1S2

**Comment by atqjp** [comment]
@takanakahiko さん、こんにちは。 @tabunmuri さんのTwitterから来ましたジョニーです。

早速ですが、服装についてです。

### 1.トップス
最近、ちょっとシルエットが大きめのTシャツがはやっているので、体型隠せると思います。
(僕もガリガリです)
- [CHAMPION×JS / チャンピオン別注 : T-1011 US T-SHIRT](https://zozo.jp/shop/journalstandard/goods-sale/42857811/?did=71232658)
- [【汗ジミ防止・抗菌防臭】USAコットン使用クルーネックTシャツ/832059](https://zozo.jp/shop/rageblue/goods-sale/40057592/?did=67340590)
- [【WEB限定】１４Ｓ／－天竺ビッグシルエットＴシャツ　半袖
](https://zozo.jp/shop/nanouniverse/goods-sale/42619716/?did=70905916)

白・黒・オリーブ・ネイビーあたりの色があると使いやすいと思います！
@tabunmuri さんも参考にどうぞ。

### 2.パンツ
上がゆったりめなので、基本下はシュッとした感じが良いかなと思います。
夏だったら綿麻の生地とかだと涼しいですよ！
- [綿麻スーパーライトイージーパンツ](https://zozo.jp/shop/nanouniverse/goods-sale/43849472/?did=72733741)
- [【WEB限定】OS★★T/R 2P EASY テーパードパンツ / アンクルパンツ](https://zozo.jp/shop/greenlabel/goods/19900993/?did=47235009)
→こういうオリーブ色は、白とかネイビーTシャツつ合わせやすい、夏っぽいのでおすすめです！
- [ストレートチノパンツ/［MEN］](https://zozo.jp/shop/zozo/goods-sale/42962820/?did=71496799)
→ちょっと太めもありですね、他細めのジーパンでもいいと思います。

短パンもありますが、抵抗ありますか？

### 3.スニーカー・サンダル
履いている靴がダザいと台無しですよね。。僕はNew Balanceマンなので、推しではありますが、高いし、それ以外にも沢山あります。
**基本的にスニーカー・サンダルはブランドによってサイズ感が若干違うので、
オンラインでの購入はおすすめしません。店舗で試着しましょう。**

#### 3-1.スニーカー
- [New balance ML574](https://zozo.jp/shop/jackandmarie/goods/34652915/?did=59797634)
→グレーは服の色決めるときに使いやすいと思います。ニューバランスはMADE IN USA,MADE IN ENGLANDと他にもありまして、興味があればぜひ→ [こちら](https://zozo.jp/shop/newbalance/goods-sale/24483186/?did=45167934)
- [ASICS GELSAGA](https://zozo.jp/shop/asicstiger/goods-sale/41395208/?did=69218127&rid=1080)
→ネイビーも使いやすくて飽きないと思います。

#### 3-2.サンダル
- [TEVA（テバ）HURRICANE（ハリケーン） XLT2　スポーツサンダル](https://zozo.jp/shop/classicalelf/goods/31989048/?did=69398174&rid=1203)
→男女問わず履いてる、ド定番の黒がおすすめです！シンプルで使いやすい
- [SHAKA / シャカ HIKER](https://zozo.jp/shop/edifice/goods-sale/42787780/?did=71130526)
→ちょっと変わっていますが、肌の露出部分が少なく、カジュアルになり過ぎないので一押しです！SHAKAはいいぞ。（僕も別シリーズですが持っています）

サンダルは基本的に夏しか履かないので、めちゃめちゃ長持ちします。
僕はもう同じやつ6年位履いてます。だからちょっといいヤツ買って長く履くのがおすすめです。

最後に、
### 夏物は7月がセール時期なので、今すぐ買いに行きましょう！！！ 👍 👍

Enjoy your Summer !  🌞 🍹 😎

**Comment by hecateball** [comment]
隣りにいる人が「モテたいなら開発合宿とかきてる場合じゃない」っていってました！

（ごめんなさいごめんなさいごめんなさい）
#mokumoku_onsen

**Comment by tabunmuri** [comment]
＜●＞＜●＞

**Comment by 8845musign** [comment]
腹筋ローラーを個人的に布教しているものです。

筋トレするなら以下の腹筋ローラーがおすすめです。

https://www.amazon.co.jp/dp/B00ZUXEQ0C/

1. 膝マット付きである
2. 滑りが大変良い
3. 価格が安い

いくつか腹筋ローラーを使い捨ててきましたがこれが一番だと思っております。

腹筋ローラーのおかげで私は男にモテるようになりました！

**Comment by takanakahiko** [comment]
@atqjp うおおおおおおおおおおお，ありがとうございます！！！！！
具体的なアドバイス，大変助かります...！参考に服を買おうと思います！

Summer，Enjoy します...!

**Comment by frecce** [comment]
- 髪型を真ん中分けしない
  - 尖った顔してるのでより強調されてカイジみたいな印象になる
  - 日本人の頭は四角いので、真ん中分けすると元々出っ張ってるところにさらに髪をもることになる
  - すると、尖った顔が強調されて▽みたいな印象になる。
  - 爬虫類とかハンターっぽい印象が強くなるので、そういう印象を狙うならあり（まさにカイジ
- 服装は何でも良いがとにかく清潔でシワのないもの
  - Tシャツジーンズでもいい
  - とにかくきれいなもの、襟がよれてないもの

**Comment by myun2** [comment]
青ひげについてですが、僕個人の場合電気シェーバーからカミソリにする事によりかなり改善しました。
カミソリの方が深剃り出来ると思われます。また電気シェーバーで深剃りをしようとすると、念入りに上下に動かす必要があり、これがかえって青ひげを増長している気がします（肌への刺激が強い）

枚数は2枚刃を使っています。髭が濃いせいか枚数が多いものだと引っかかるので。
そんなに色々試したわけではないですが、最初に買ったBICが良かったのでそのまま愛用しています

https://www.amazon.co.jp/dp/B0022NHAZG

最初は加減が難しいかも知れませんが、慣れると青ひげからはおさらばです
ちなみに旅館においてあるような二枚刃だとひりついて仕方ありませんね…

**Comment by myun2** [comment]
「姿勢」については、ウォーキングでかなり改善した（と思っている）のでこちらもおすすめします。
一ヶ月ほどの間、ダイエットも兼ねて家まで歩いて帰る（2～3時間ほど）を繰り返した（毎日ではないけど。2日に1ぺんほど）ところかなり姿勢も改善したので。

体幹が鍛えられる、と言う奴かも知れません。結局、人類の最も基本的な動作なので。筋トレなどで局所的に鍛えるよりも全身の筋肉がバランス良く使われると言ったところでしょうか。

贅肉（もしあればですが…）も落ちるし一石二鳥です。

**Comment by myun2** [comment]
ゴッソ…についてですが、使ったことがないので分かりませんが、かえって「めちゃくちゃ太いやつ」が生えて来ないか等のリスクもあるかと思います。
「ゴッソ」で全抜きせずとも、毎朝鏡を見て、顔を左右に少し動かし「鼻毛が出てないか（出てれば鼻毛切りで切る）」で十分かと思います。

多分ゴッソで全抜きするよりも、「この男の人は毎朝ちゃんと鏡を見て、自分の身だしなみをチェックしているだろうか？」と言う方が、女性からの評価対象だとは思いますので…

**Comment by myun2** [comment]
とかいってみました（ちなみに @tabunmuri さんの知り合いみたいなものです）

**Comment by hotuta** [comment]
こんにちは！こんにちは！
IMO(個人的な意見ですが、)、 @takanakahiko くんはモテる要素は十分にあるかなと思っています。
ただ、@takanakahiko くんには経済的な問題があり、モテるモテないというよりも、経済的な問題をどう解決するか、自身のマネーマネジメント力を高めていくのが最優先ではないでしょうか。
仮にモテるようになったとしても、いつか経済的な問題によって振られるなどなど様々なことを経験することになるかと思います。
下手に結婚してバツイチになると悲惨なことになるので、バツイチになって欲しくないなと思ってコメントしました。
今最優先にやるべきことは何かをしっかり考えて、ベストを尽くして欲しいなと思います。

**Comment by takanakahiko** [comment]
@8845musign 腹筋ローラー良さそうですね！早速購入します！
ってアレ...? 男にモテる...?

**Comment by takanakahiko** [comment]
@frecce ありがとうございます！
そういえば顔が長いので，ソレに応じた髪型等への配慮も必要ですね！

服についてもありがとうございます！とにかく清潔感を意識します！

**Comment by takanakahiko** [comment]
@myun2 いろいろとありがとうございます！

ひげに関してはとても助かりました！
とりあえず相性等の確認をするために10本のものを購入しました！
https://www.amazon.co.jp/dp/B0022NHAYW

姿勢はそうですね, 大学の最寄りから大学まで40分程度歩けるので継続してみようと思います．
普段が座ってばっかりなので意識してあるいたほうが良さそうですね．

たしかにゴッソをやることが根本的な解決ではないですね！
普段から鏡で自分の容姿に気をかけるようにします．
(振り返ってみれば，楽してモテようとしている自分がいたかもしれません)

**Comment by takanakahiko** [comment]
@hotuta ありがとうございます！

私の「モテたい」のコンテキストは，直接的な「誰かとお付き合いしたい」というものより「人に紹介していただけるようなまっとうな人間になりたい」みたいなものなので，気軽にアドバイスいただけたらと思って今回このIssueを建てた次第です．

**Comment by takanakahiko** [comment]
> 差し歯が黒ずんでいるので，まともなやつにリプレイスする

リプレイスした

>  姿勢が悪いので整体とかに行く

アーロンチェア買ったら姿勢が良くなりました

**Comment by takanorip** [comment]
> おしゃれな靴を買う

好みに合うかわかりませんが僕の好きな靴ブランドをいくつか紹介します。参考にしてもらえたら嬉しいです。
スーツとか着ない場合でもカジュアルな革靴とかあるとおしゃれに見えるかもしれません。

[Rivieras](https://www.aman.ne.jp/brands/rivieras/)
スリッポンのブランドです。スリッポンとかエスパドリーユは安っぽい見た目のものが多い気がしますが、これはとてもかっこよく作りもしっかりしています。サンダルより見た目おしゃれで歩きやすく、普通の靴より涼しいし洗いやすいのでとても重宝します。

[Camper](https://www.camper.com/ja_JP/)
丸みのあるデザインが特徴のブランドです。左右非対称な靴とかスニーカーっぽい革靴とか面白い靴が多くて好きです。

[Clarks](https://www.clarks.co.jp/)
デザートブーツが有名なブランドですがスニーカーなども扱ってます。メンズブーツはゴツい見た目のものが多いですが、Clarksのデザートブーツはシンプルで使い勝手が良いです。

**Comment by takanakahiko** [comment]
@takanorip ありがとうございます！
割と僕から見ても好みのものが多かったですし、何より靴屋の靴をしっかり吟味する機会になってよかったです。

あの、なんていうか、やっぱりお金はかかるものなんですね…。今まで本当にコスパしか気にしてこなかったので、純粋にびっくりしています。かけるところにはしっかりお金かけていこうと思いました。

**Comment by takanorip** [comment]
> やっぱりお金はかかるもの

わかります…。僕も最初はけっこうビックリしたんですけど、良い靴は手入れすれば長く履けるものが多いので、長い目で見るとけっこうコスパ良い気がします。気にいるものが見つかるといいですね！

**Comment by takanakahiko** [comment]
実家に腹筋ローラを置いてきてしまったので、Amazonで購入しました

**Comment by yacchiDAO** [comment]
> 青ひげがすごいので脱毛なりをする

6回コースで医療脱毛を始めた者です。（予算は数万程度）

これまでに2ヶ月おきに3回施術した実態と感想です。

- 照射後1週間でポロポロ抜け落ち始めて楽しい
- 照射後2ヶ月程度で復活する
- 上記期間のひげの状態
  - ひげが細くなる → **剃った後の見た目、触り心地が変わる**
  - ひげを剃る頻度が減る → そもそも肌に優しい
- 照射自体はギリギリ耐えられる痛みを10分程度浴びる
- 照射回数を重ねるほどひげ自体はJOJOに細くはなる

その他Tips
- ひげを医療脱毛で完全に消すのは10回以上やる必要があるらしい
- 一回の施術で毛量が10%減少するらしい
- 契約したら、予約時間に通院して15分程度終わるので時間はかからない

**Comment by takanakahiko** [comment]
@yacchiDAO ガチ知見ありがとうございます...！
ひげが細くなるのマジで大事ですね...。完全に剃ったはずなのに青い、みたいな現象がしんどかったので。
前向きにやってみようと思います！（こんどお店を教えてほしい）

**Comment by takanakahiko** [comment]
同期より紹介いただきました
https://www.amazon.co.jp/dp/B00UH97O4E

**Comment by TakutoYoshikai** [comment]
ファッションに詳しい方にレビュー貰ってOKだったので共有します。

脱オタファッション(男) https://scrapbox.io/takuto-memo/%E8%84%B1%E3%82%AA%E3%82%BF%E3%83%95%E3%82%A1%E3%83%83%E3%82%B7%E3%83%A7%E3%83%B3(%E7%94%B7)

**Comment by takanakahiko** [comment]
こんなIssueのためにOGP発行してもらうの申し訳なくなってきたな
![image](https://user-images.githubusercontent.com/10114717/115900898-784b0280-a49b-11eb-99d6-bdc43d57d43f.png)

**Comment by takanakahiko** [comment]
最近モテてるので閉じます！
